### ISSUE TITLE
The token '||' is not a valid statement separator in this version.

### ISSUE THREAD

**Issue by wmuza** [Richienb/get-url-title#56]
**Describe the bug**
installing the package via npm i get-url-title is leading to this error `The token '||' is not a valid statement separator in this version.`

**To Reproduce**
Steps to reproduce the behavior: npm i get-url-title on node v14.19.0

**Screenshots**
![image](https://user-images.githubusercontent.com/35020495/185351098-596753e1-1cc8-43e8-8240-95d092fc2d60.png)

**Desktop (please complete the following information):**

-   OS: Windows
-   Node: v14.19.0

**Comment by Richienb** [comment]
Read the error again. In the first and second line of the screenshot, you run a command. The error is directly referencing the `||` on the second line. This is because `||` is [not supported in PowerShell](https://stackoverflow.com/questions/65627536/the-token-is-not-a-valid-statement-separator-in-this-version). See also: https://github.com/remy/nodemon/issues/2007

**Comment by wmuza** [comment]
I have gone through this but this prevented my deployments in Google Cloud Run. 
![image](https://user-images.githubusercontent.com/35020495/185367022-692dad96-1ce6-49b7-b7ff-f3a36c9a60a8.png)

Anyway thank you for the quick response
